version: "3"

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always

    rabbitmq:
        image: "rabbitmq"
        ports:
            - "5672:5672"