version: "3"

services:
  redis:
    image: redis
    ports:
        - "6379:6379"
    restart: always

  rabbitmq:
    image: "rabbitmq-delayed"
    ports:
        - "5672:5672"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
        - REDIS_HOSTS=local:redis:6379
    ports:
        - "8081:8081"

  fhirstore:
    image: synaneticsltd/synfhir-store:linux-v2.5.0
    restart: always
    environment:
      - ADVANCED_CONSENT=false
      - ASYNCPAGESIZE=1000
      - ASYNCEXPIRES=7
      - AUDIT_ACCESS=true
      - CACHEEXPIRES=600
      - FHIR_STORE_ASYNC_URL=https://fhir.staging.helm.org/fhir/stu4/bulk
      - FHIR_STORE_BASE_URL=https://fhir.staging.helm.org/fhir/stu3
      - LOGGER=true
      - LOGLEVEL=debug
      - MAX_CLIENTS=1
      - MAXPAGESIZE=1000
      - METRICSENABLE=false
      - NODE_ENV=development
      - PG_CONNECTION=postgresql://postgres:postgres@fhir-database:5432
      - PORT=3000
      - SERVICEDIR=services
      - TAG={"system":"https://yhcr.nhs.uk/Source","code":"YHCR","display":"YHCR Portal"}
      - VALIDATE_JWT=false
    ports:
      - "3001:3000"

  fhir-database:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5443:5432"

  prometheus:
    image: prom/prometheus:v2.16.0
    ports:
        - 9090:9090
    volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
        - 3031:3000
    depends_on:
        - prometheus
    environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  helm-yhcr:
    build:
      dockerfile: YhcrDockerfile  
      context: ./run/k8s/local
    ports:
      - 3443:443
    volumes:
      - ./keys/helm-development1-bb8d6ad3e477.json:/tmp/account-key.json
    environment:
      - CA_CERT=gcp_sos_ca_cert
      - TARGET=http://host.docker.internal:8090
      - CERT=gcp_sos_dataprovider_server_cert
      - KEY=gcp_sos_dataprovider_server_key
      - PASSPHRASE=gcp_sos_dataprovider_server_passphrase
      - SERVERNAME=localhost
      - NODE_ENV=development
      - TLSMA=ENABLED
      - GCP_PROJECT_ID=helm-development1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/account-key.json
